import fs from "fs";
import path from "path";

const extra = [
  {"iso2":"TC","iso3":"TCA","nameEn":"Turks and Caicos","slug":"turks-and-caicos","region":"Americas","languages":["en"],"currencyCode":"USD","timeZonePrimary":"America/Grand_Turk","internetNotes":"Decent infrastructure for a small territory. Digicel and Flow are providers. Good coverage in Providenciales. USD-based economy.","vpnNotes":"VPNs are fully legal. British Overseas Territory with open internet. Used by tourists and the financial services sector.","paymentNotes":"USD-based. Card payments accepted in tourist areas. International payment methods work for online purchases.","travelNotes":"Good Wi-Fi in resort hotels. Grace Bay area well-connected. Smaller islands may have limited coverage.","riskFlags":["tourist-wifi"]},
  {"iso2":"KY","iso3":"CYM","nameEn":"Cayman Islands","slug":"cayman-islands","region":"Americas","languages":["en"],"currencyCode":"KYD","timeZonePrimary":"America/Cayman","internetNotes":"Good infrastructure. Flow and Digicel are providers. Strong connectivity driven by financial services industry.","vpnNotes":"VPNs are fully legal. British Overseas Territory with open internet. Major offshore financial center driving strong VPN adoption.","paymentNotes":"KYD-based. USD widely accepted. Card payments common. International payment methods accepted everywhere.","travelNotes":"Good Wi-Fi in George Town and Seven Mile Beach hotels. Excellent coverage for a Caribbean territory.","riskFlags":["tourist-wifi"]},
  {"iso2":"BM","iso3":"BMU","nameEn":"Bermuda","slug":"bermuda","region":"Americas","languages":["en"],"currencyCode":"BMD","timeZonePrimary":"Atlantic/Bermuda","internetNotes":"Good infrastructure. One Communications and Digicel are providers. Fiber available in Hamilton. Small island with comprehensive coverage.","vpnNotes":"VPNs are fully legal. British Overseas Territory. Financial services sector drives VPN adoption. Open internet policy.","paymentNotes":"BMD-based (pegged to USD). Card payments common. International payment methods accepted for online services.","travelNotes":"Good Wi-Fi throughout this small island. Hotels, restaurants, and public areas well-connected.","riskFlags":["tourist-wifi"]},
  {"iso2":"GI","iso3":"GIB","nameEn":"Gibraltar","slug":"gibraltar","region":"Europe","languages":["en"],"currencyCode":"GIP","timeZonePrimary":"Europe/Gibraltar","internetNotes":"Good infrastructure for a small territory. Gibtelecom is the main provider. Compact size means comprehensive coverage.","vpnNotes":"VPNs are fully legal. British Overseas Territory with open internet. Online gambling industry drives strong digital infrastructure.","paymentNotes":"GIP-based (pegged to GBP). GBP accepted. Card payments common. International payment methods work seamlessly.","travelNotes":"Excellent Wi-Fi coverage throughout this tiny territory. Hotels and restaurants all connected.","riskFlags":["tourist-wifi"]},
  {"iso2":"FO","iso3":"FRO","nameEn":"Faroe Islands","slug":"faroe-islands","region":"Europe","languages":["fo","da"],"currencyCode":"DKK","timeZonePrimary":"Atlantic/Faroe","internetNotes":"Good broadband for a remote archipelago. Føroya Tele is the main provider. Fiber available in Tórshavn. Submarine cables ensure decent connectivity.","vpnNotes":"VPNs are fully legal. Danish self-governing territory with open internet. No restrictions on VPN use.","paymentNotes":"DKK-based. Card payments common. Nearly cashless like mainland Denmark. International payment methods accepted.","travelNotes":"Good Wi-Fi in Tórshavn hotels. Remote villages and smaller islands may have limited coverage. Beautiful but isolated.","riskFlags":["tourist-wifi"]},
  {"iso2":"GL","iso3":"GRL","nameEn":"Greenland","slug":"greenland","region":"Americas","languages":["kl","da"],"currencyCode":"DKK","timeZonePrimary":"America/Nuuk","internetNotes":"Limited infrastructure given vast size. TELE Greenland is the sole provider. Fiber in Nuuk. Remote communities rely on satellite connections.","vpnNotes":"VPNs are fully legal. Danish self-governing territory. Internet access challenged by geography more than policy.","paymentNotes":"DKK-based. Card payments in Nuuk and larger towns. Cash needed in smaller settlements.","travelNotes":"Wi-Fi in Nuuk hotels. Remote settlements and wilderness areas have limited or no connectivity. World's largest island with minimal infrastructure.","riskFlags":["tourist-wifi"]},
  {"iso2":"NC","iso3":"NCL","nameEn":"New Caledonia","slug":"new-caledonia","region":"APAC","languages":["fr"],"currencyCode":"XPF","timeZonePrimary":"Pacific/Noumea","internetNotes":"Decent infrastructure. OPT is the main provider. Good coverage in Noumea. French overseas territory with undersea cable connections.","vpnNotes":"VPNs are fully legal. French territory with open internet. French digital rights and GDPR-adjacent protections apply.","paymentNotes":"XPF (CFP franc) based. Card payments in Noumea. Cash important outside the capital. Euro-pegged currency.","travelNotes":"Good Wi-Fi in Noumea hotels. Outer islands and rural areas have limited connectivity. French-speaking territory.","riskFlags":["tourist-wifi"]},
  {"iso2":"PF","iso3":"PYF","nameEn":"French Polynesia","slug":"french-polynesia","region":"APAC","languages":["fr","ty"],"currencyCode":"XPF","timeZonePrimary":"Pacific/Tahiti","internetNotes":"Decent infrastructure for remote Pacific islands. VINI is the main provider. Good coverage in Papeete, Tahiti. Outer islands have limited connectivity.","vpnNotes":"VPNs are fully legal. French territory with open internet. Submarine cable connections improving speeds.","paymentNotes":"XPF (CFP franc) based. Card payments in tourist areas. Cash important on smaller islands.","travelNotes":"Good Wi-Fi in Tahiti and Bora Bora resorts. Remote atolls have satellite-only connectivity.","riskFlags":["tourist-wifi"]},
  {"iso2":"GU","iso3":"GUM","nameEn":"Guam","slug":"guam","region":"APAC","languages":["en","ch"],"currencyCode":"USD","timeZonePrimary":"Pacific/Guam","internetNotes":"Good infrastructure as a US territory. GTA, IT&E, and Docomo Pacific are providers. US regulations and standards apply. Military presence drives infrastructure.","vpnNotes":"VPNs are fully legal as a US territory. Same ISP privacy landscape as mainland US. VPN recommended for privacy.","paymentNotes":"USD-based. All US payment methods accepted. Card payments common.","travelNotes":"Good Wi-Fi in Tumon Bay hotels and resorts. Compact island with decent coverage throughout.","riskFlags":["tourist-wifi"]},
  {"iso2":"VI","iso3":"VIR","nameEn":"US Virgin Islands","slug":"us-virgin-islands","region":"Americas","languages":["en"],"currencyCode":"USD","timeZonePrimary":"America/Virgin","internetNotes":"Decent infrastructure. Viya and Choice are providers. Good coverage in Charlotte Amalie and resort areas. US territory standards.","vpnNotes":"VPNs are fully legal as a US territory. Same privacy landscape as mainland US.","paymentNotes":"USD-based. Card payments common in tourist areas. All US payment methods accepted.","travelNotes":"Good Wi-Fi in resort hotels on St. Thomas, St. Croix, and St. John. Remote beach areas may have weaker signals.","riskFlags":["tourist-wifi"]},
  {"iso2":"AS","iso3":"ASM","nameEn":"American Samoa","slug":"american-samoa","region":"APAC","languages":["sm","en"],"currencyCode":"USD","timeZonePrimary":"Pacific/Pago_Pago","internetNotes":"Limited infrastructure. ASTCA is the main provider. Coverage in Pago Pago. Remote Pacific territory with bandwidth constraints.","vpnNotes":"VPNs are fully legal as a US territory. Limited internet bandwidth may affect VPN performance.","paymentNotes":"USD-based. Cash dominant. Limited card acceptance outside main businesses.","travelNotes":"Basic Wi-Fi in Pago Pago hotels. Very limited coverage in outer areas. Remote Pacific territory.","riskFlags":["tourist-wifi"]},
  {"iso2":"MP","iso3":"MNP","nameEn":"Northern Mariana Islands","slug":"northern-mariana-islands","region":"APAC","languages":["en","ch"],"currencyCode":"USD","timeZonePrimary":"Pacific/Guam","internetNotes":"Decent infrastructure. IT&E and Docomo Pacific are providers. Good coverage in Saipan. US Commonwealth with improving connectivity.","vpnNotes":"VPNs are fully legal as a US territory. Same privacy regulations as mainland US.","paymentNotes":"USD-based. Card payments in tourist areas. All US payment methods accepted on Saipan.","travelNotes":"Good Wi-Fi in Saipan hotels and resorts. Tinian and Rota have more limited connectivity.","riskFlags":["tourist-wifi"]}
];

const filePath = path.join(process.cwd(), "src", "data", "countries.json");
const existing = JSON.parse(fs.readFileSync(filePath, "utf-8"));
const existingIso2 = new Set(existing.map((c: { iso2: string }) => c.iso2));
const existingSlugs = new Set(existing.map((c: { slug: string }) => c.slug));

let added = 0;
for (const c of extra) {
  if (!existingIso2.has(c.iso2) && !existingSlugs.has(c.slug)) {
    existing.push(c);
    added++;
  }
}

fs.writeFileSync(filePath, JSON.stringify(existing, null, 2) + "\n");
console.log(`Added ${added}. Total: ${existing.length}`);
