import fs from "fs";
import path from "path";

const extra = [
  {"iso2":"LI","iso3":"LIE","nameEn":"Liechtenstein","slug":"liechtenstein","region":"Europe","languages":["de"],"currencyCode":"CHF","timeZonePrimary":"Europe/Vaduz","internetNotes":"Excellent broadband for a microstate. Telecom Liechtenstein provides fiber with very fast speeds. Strong Swiss-adjacent digital infrastructure and privacy laws.","vpnNotes":"VPNs are fully legal in Liechtenstein. The principality benefits from Swiss-like privacy protections. No restrictions on VPN use or internet access.","paymentNotes":"CHF-based. Card payments widely accepted. Swiss payment infrastructure. International payment methods work seamlessly for VPN subscriptions.","travelNotes":"Excellent Wi-Fi in hotels and restaurants. Very small country with comprehensive coverage. Close proximity to Swiss and Austrian infrastructure.","riskFlags":["tourist-wifi"]},
  {"iso2":"MC","iso3":"MCO","nameEn":"Monaco","slug":"monaco","region":"Europe","languages":["fr"],"currencyCode":"EUR","timeZonePrimary":"Europe/Monaco","internetNotes":"Excellent broadband infrastructure. Monaco Telecom provides fiber with fast speeds. One of the most connected microstate nations with comprehensive 5G coverage.","vpnNotes":"VPNs are fully legal in Monaco. The principality has an open internet policy. Used by the financial services sector and wealthy residents for privacy.","paymentNotes":"Euro-based. Card payments universal. All international payment methods accepted. Premium pricing for local services but VPN subscriptions are standard international rates.","travelNotes":"Excellent Wi-Fi throughout this tiny principality. Hotels, restaurants, and public areas all well-connected. French Riviera infrastructure extends into Monaco.","riskFlags":["tourist-wifi"]},
  {"iso2":"AD","iso3":"AND","nameEn":"Andorra","slug":"andorra","region":"Europe","languages":["ca"],"currencyCode":"EUR","timeZonePrimary":"Europe/Andorra","internetNotes":"Good broadband for a small nation. Andorra Telecom is the sole provider. Fiber available in main towns. Growing digital nomad appeal due to favorable tax policies.","vpnNotes":"VPNs are fully legal in Andorra. No restrictions on internet access. Growing tech-aware population attracted by favorable tax regime and European quality of life.","paymentNotes":"Euro-based. Card payments common in larger establishments. Cash still used in smaller shops. International payment methods work for online VPN purchases.","travelNotes":"Good Wi-Fi in hotels and ski resorts. Coverage adequate in Andorra la Vella and main towns. Mountain areas may have limited connectivity. Popular ski destination.","riskFlags":["tourist-wifi"]},
  {"iso2":"BZ","iso3":"BLZ","nameEn":"Belize","slug":"belize","region":"Americas","languages":["en","es"],"currencyCode":"BZD","timeZonePrimary":"America/Belize","internetNotes":"Basic but improving internet infrastructure. BTL and Speednet are providers. Good coverage in Belize City and tourist areas. Rural areas and cayes have limited connectivity.","vpnNotes":"VPNs are fully legal in Belize. English-speaking nation popular with expats and retirees. No government restrictions on internet access or VPN usage.","paymentNotes":"BZD-based (pegged to USD). USD widely accepted. Card payments accepted in tourist areas. Cash important in local businesses. International payment methods work online.","travelNotes":"Wi-Fi in hotels in Belize City, San Pedro, and Caye Caulker. Island connectivity varies. Rural and jungle areas have very limited or no internet. Starlink growing.","riskFlags":["tourist-wifi"]},
  {"iso2":"GY","iso3":"GUY","nameEn":"Guyana","slug":"guyana","region":"Americas","languages":["en"],"currencyCode":"GYD","timeZonePrimary":"America/Guyana","internetNotes":"Improving internet infrastructure driven by oil revenues. GTT and Digicel are providers. Georgetown has decent coverage. Interior and Amazonian regions have very limited connectivity.","vpnNotes":"VPNs are fully legal in Guyana. English-speaking nation with no restrictions on internet access. Growing economy attracting international workers who drive VPN adoption.","paymentNotes":"GYD-based. Cash dominant. Card payments accepted in Georgetown hotels and major businesses. International payment methods available for online VPN purchases.","travelNotes":"Wi-Fi in Georgetown hotels. Kaieteur Falls and interior regions have very limited or no connectivity. Coastal areas generally connected. Mobile data coverage in main towns.","riskFlags":["tourist-wifi"]},
  {"iso2":"SR","iso3":"SUR","nameEn":"Suriname","slug":"suriname","region":"Americas","languages":["nl"],"currencyCode":"SRD","timeZonePrimary":"America/Paramaribo","internetNotes":"Basic internet infrastructure. Telesur is the main provider. Decent coverage in Paramaribo. Interior and rainforest regions have very limited connectivity.","vpnNotes":"VPNs are fully legal in Suriname. Dutch-speaking nation with no restrictions on internet access. Small but growing online community driving VPN awareness.","paymentNotes":"SRD-based. Cash dominant. Card payments accepted in Paramaribo hotels and major businesses. International payment methods needed for online VPN subscriptions.","travelNotes":"Wi-Fi in Paramaribo hotels and some restaurants. Interior and nature reserves have very limited connectivity. Mobile coverage concentrated along the coast.","riskFlags":["tourist-wifi"]},
  {"iso2":"BB","iso3":"BRB","nameEn":"Barbados","slug":"barbados","region":"Americas","languages":["en"],"currencyCode":"BBD","timeZonePrimary":"America/Barbados","internetNotes":"Good internet for a Caribbean island. FLOW and Digicel are providers. The Barbados Welcome Stamp visa attracted remote workers. Good broadband in urban areas.","vpnNotes":"VPNs are fully legal in Barbados. The Welcome Stamp digital nomad visa program has increased VPN awareness among remote workers. No restrictions on internet access.","paymentNotes":"BBD-based (pegged to USD). Card payments widely accepted in tourist areas. International payment methods work well for online VPN and subscription purchases.","travelNotes":"Good Wi-Fi in hotels and restaurants. The small island has decent coverage throughout. Some beaches and remote areas may have weaker signals. Digital nomad infrastructure growing.","riskFlags":["tourist-wifi"]},
  {"iso2":"MV","iso3":"MDV","nameEn":"Maldives","slug":"maldives","region":"APAC","languages":["dv","en"],"currencyCode":"MVR","timeZonePrimary":"Indian/Maldives","internetNotes":"Good coverage in Male and resort islands. Dhiraagu and Ooredoo are providers. Resort islands typically have their own Wi-Fi infrastructure. Speeds vary by island.","vpnNotes":"VPNs are legal for personal use in the Maldives. Some content is filtered by the government. VoIP services may be restricted. VPN commonly used by tourists for communication.","paymentNotes":"MVR-based. USD accepted in resort islands. Card payments standard at resorts. Cash needed for local island visits. International payment methods work online.","travelNotes":"Resort Wi-Fi generally good but varies by property. Male has decent coverage. Local islands have more limited connectivity. VPN useful for VoIP calls from resorts.","riskFlags":["restricted-platforms","tourist-wifi"]},
  {"iso2":"BT","iso3":"BTN","nameEn":"Bhutan","slug":"bhutan","region":"APAC","languages":["dz"],"currencyCode":"BTN","timeZonePrimary":"Asia/Thimphu","internetNotes":"Growing internet infrastructure in this Himalayan kingdom. Bhutan Telecom and TashiCell are providers. Good coverage in Thimphu and Paro. Mountain areas have very limited connectivity.","vpnNotes":"VPNs are legal in Bhutan. The government monitors internet content but VPN use is not restricted. Limited but growing internet adoption with no significant VPN blocking.","paymentNotes":"BTN-based (pegged to INR). Cash dominant. Card acceptance very limited outside major hotels. International payment methods needed for online VPN purchases. Prepay before visiting.","travelNotes":"Wi-Fi in hotels in Thimphu and Paro. Mountain monasteries and trekking routes have no connectivity. Daily tourist fee applies. Download everything offline before remote areas.","riskFlags":["tourist-wifi"]},
  {"iso2":"MG","iso3":"MDG","nameEn":"Madagascar","slug":"madagascar","region":"Africa","languages":["mg","fr"],"currencyCode":"MGA","timeZonePrimary":"Indian/Antananarivo","internetNotes":"Limited but growing internet market. Orange, Airtel, and Telma are providers. Coverage concentrated in Antananarivo. Rural areas and national parks have very limited connectivity.","vpnNotes":"VPNs are legal in Madagascar. No significant restrictions on internet access. Growing mobile internet adoption but VPN awareness is still limited outside expat communities.","paymentNotes":"MGA-based. Cash dominant. Card payments limited to major hotels in Antananarivo. Mobile money (Mvola, Orange Money) growing. International payment methods for online purchases.","travelNotes":"Wi-Fi in Antananarivo hotels. National parks and wildlife areas have very limited or no connectivity. Download offline maps and content before leaving the capital.","riskFlags":["tourist-wifi"]},
  {"iso2":"FI","iso3":"FIN","nameEn":"Finland","slug":"finland","region":"Europe","languages":["fi","sv","en"],"currencyCode":"EUR","timeZonePrimary":"Europe/Helsinki","internetNotes":"Excellent broadband and mobile coverage. Elisa, DNA, and Telia are major providers. Internet access is considered a legal right in Finland. One of the most connected countries globally.","vpnNotes":"VPNs are fully legal in Finland. The country has strong privacy traditions and tech-savvy population. VPN use is widespread among privacy-conscious Finns and tech professionals.","paymentNotes":"Euro-based. Nearly cashless society. Card and mobile payments dominant. MobilePay and Pivo widely used. International payment methods work seamlessly.","travelNotes":"Excellent Wi-Fi coverage across Finland. Public libraries, cafes, trains, and even remote Lapland areas increasingly connected. Helsinki is one of Europe's most connected cities.","riskFlags":["tourist-wifi"]}
];

const filePath = path.join(process.cwd(), "src", "data", "countries.json");
const existing = JSON.parse(fs.readFileSync(filePath, "utf-8"));
const existingIso2 = new Set(existing.map((c: { iso2: string }) => c.iso2));

let added = 0;
for (const c of extra) {
  if (!existingIso2.has(c.iso2)) { existing.push(c); added++; }
}

fs.writeFileSync(filePath, JSON.stringify(existing, null, 2) + "\n");
console.log(`Added ${added}. Total: ${existing.length}`);
