import fs from "fs";
import path from "path";

const extra = [
  {"iso2":"GN","iso3":"GIN","nameEn":"Guinea","slug":"guinea","region":"Africa","languages":["fr"],"currencyCode":"GNF","timeZonePrimary":"Africa/Conakry","internetNotes":"Limited internet market. Orange and MTN are carriers. Coverage in Conakry. Government has imposed internet shutdowns during political events and elections.","vpnNotes":"VPN use is common during internet restrictions. Government blocks social media during political tensions. VPN essential during shutdown periods.","paymentNotes":"GNF-based. Cash dominant. Orange Money growing. Very limited international card acceptance. Prepay for VPN services before visiting.","travelNotes":"Limited Wi-Fi in Conakry hotels. Rural areas have very limited connectivity. Internet shutdowns can occur without warning.","riskFlags":["censorship","restricted-platforms","tourist-wifi"]},
  {"iso2":"GM","iso3":"GMB","nameEn":"Gambia","slug":"gambia","region":"Africa","languages":["en"],"currencyCode":"GMD","timeZonePrimary":"Africa/Banjul","internetNotes":"Limited internet infrastructure. Africell, QCell, and Comium are carriers. Coverage in Banjul and main towns. Government imposed a complete internet shutdown during 2016 elections.","vpnNotes":"VPN use grew after the 2016 internet shutdown. English-speaking nation with growing mobile internet adoption. Government has restricted access during political events.","paymentNotes":"GMD-based. Cash dominant. Mobile money growing. Very limited card acceptance. International payment methods needed for online VPN purchases.","travelNotes":"Wi-Fi in Banjul hotels and tourist resorts. Beach resort areas generally connected. Rural areas have limited coverage.","riskFlags":["restricted-platforms","tourist-wifi"]},
  {"iso2":"MK","iso3":"MKD","nameEn":"North Macedonia","slug":"north-macedonia","region":"Europe","languages":["mk","sq"],"currencyCode":"MKD","timeZonePrimary":"Europe/Skopje","internetNotes":"Good coverage for the region. Makedonski Telekom, A1, and Lycamobile are providers. Affordable pricing with decent speeds in Skopje and expanding fiber network.","vpnNotes":"VPNs are fully legal. No restrictions on internet access. Growing IT outsourcing sector drives adoption among tech professionals and remote workers.","paymentNotes":"MKD-based. Card payments growing in Skopje. Cash common in smaller cities. International payment methods available for online VPN and subscription purchases.","travelNotes":"Good Wi-Fi in Skopje and Ohrid hotels and cafes. Lake Ohrid tourist area connected. Rural and mountain areas may have limited coverage.","riskFlags":["tourist-wifi"]},
  {"iso2":"DJ","iso3":"DJI","nameEn":"Djibouti","slug":"djibouti","region":"Africa","languages":["fr","ar"],"currencyCode":"DJF","timeZonePrimary":"Africa/Djibouti","internetNotes":"Limited infrastructure. Djibouti Telecom is the sole provider. Strategic location for submarine cables but domestic internet is expensive and slow.","vpnNotes":"VPNs are legal but internet censorship exists. Government monitors internet activity. VPN useful for privacy and accessing unrestricted content.","paymentNotes":"DJF-based. Cash dominant. Very limited digital payment infrastructure. International card acceptance limited to major hotels.","travelNotes":"Wi-Fi in Djibouti City hotels. Very limited coverage outside the capital. Internet is expensive relative to the region.","riskFlags":["restricted-platforms","tourist-wifi"]},
  {"iso2":"ER","iso3":"ERI","nameEn":"Eritrea","slug":"eritrea","region":"Africa","languages":["ti","ar","en"],"currencyCode":"ERN","timeZonePrimary":"Africa/Asmara","internetNotes":"One of the least connected countries globally. EriTel is the sole provider. Internet penetration under 5%. Government controls all telecommunications.","vpnNotes":"VPN use is difficult due to extremely limited internet access. The government restricts internet severely. Among the lowest internet freedom scores globally.","paymentNotes":"ERN-based. Cash only. No digital payment infrastructure. International card acceptance nonexistent. All services must be prepaid before entering.","travelNotes":"Extremely limited internet access. Even Asmara has very slow and unreliable connectivity. Do not rely on internet access in Eritrea.","riskFlags":["censorship","restricted-platforms","tourist-wifi"]},
  {"iso2":"SS","iso3":"SSD","nameEn":"South Sudan","slug":"south-sudan","region":"Africa","languages":["en"],"currencyCode":"SSP","timeZonePrimary":"Africa/Juba","internetNotes":"Very limited infrastructure. Zain, Vivacell, and MTN are carriers. Coverage mainly in Juba. Ongoing conflict affects telecommunications infrastructure.","vpnNotes":"VPNs are legal but internet access is severely limited by infrastructure challenges. Government has restricted social media during political tensions.","paymentNotes":"SSP-based. Cash dominant. Very limited digital payment infrastructure. International payment methods essentially unavailable locally.","travelNotes":"Very limited Wi-Fi in Juba hotels. No coverage outside major towns. Conflict zones have no telecommunications. Active travel warnings.","riskFlags":["restricted-platforms","tourist-wifi"]},
  {"iso2":"BI","iso3":"BDI","nameEn":"Burundi","slug":"burundi","region":"Africa","languages":["fr","rn"],"currencyCode":"BIF","timeZonePrimary":"Africa/Bujumbura","internetNotes":"Limited internet market. Lumitel and Econet are carriers. Coverage in Bujumbura. Government has restricted internet access during political events.","vpnNotes":"VPN use is common during internet restrictions. Government has blocked social media and imposed internet shutdowns. VPN essential during political events.","paymentNotes":"BIF-based. Cash dominant. Mobile money growing. Very limited international card acceptance.","travelNotes":"Limited Wi-Fi in Bujumbura hotels. Rural areas have very limited connectivity. Internet restrictions can occur during political tensions.","riskFlags":["censorship","restricted-platforms","tourist-wifi"]},
  {"iso2":"RW2","iso3":"skip","nameEn":"skip","slug":"skip","region":"skip","languages":[],"currencyCode":"skip","timeZonePrimary":"skip","internetNotes":"skip","vpnNotes":"skip","paymentNotes":"skip","travelNotes":"skip","riskFlags":[]},
  {"iso2":"GW","iso3":"GNB","nameEn":"Guinea-Bissau","slug":"guinea-bissau","region":"Africa","languages":["pt"],"currencyCode":"XOF","timeZonePrimary":"Africa/Bissau","internetNotes":"Very limited internet infrastructure. Orange and MTN are carriers. Coverage mainly in Bissau. One of the least connected countries in West Africa.","vpnNotes":"VPNs are legal. Limited internet access makes VPN less relevant than basic connectivity. No significant government internet restrictions beyond infrastructure limitations.","paymentNotes":"XOF (CFA franc) based. Cash dominant. Very limited digital payment infrastructure. International card acceptance nonexistent outside major hotels.","travelNotes":"Very limited Wi-Fi in Bissau hotels. Rural areas and islands have no connectivity. Portuguese-speaking, similar challenges to other West African nations.","riskFlags":["tourist-wifi"]},
  {"iso2":"KG","iso3":"KGZ","nameEn":"Kyrgyzstan","slug":"kyrgyzstan","region":"APAC","languages":["ky","ru"],"currencyCode":"KGS","timeZonePrimary":"Asia/Bishkek","internetNotes":"Decent internet in Bishkek. MegaCom, Beeline, and O! are carriers. Growing mobile internet adoption. Government has restricted internet during political events.","vpnNotes":"VPN use is legal and common. Government has blocked social media during protests. Bishkek has a growing digital nomad community attracted by visa-free access and low costs.","paymentNotes":"KGS-based. Cash dominant but card payments growing in Bishkek. Mobile banking via Mbank growing. International cards accepted at major businesses.","travelNotes":"Good Wi-Fi in Bishkek hotels and cafes. Mountain and rural areas have limited coverage. Issyk-Kul lake area has basic connectivity in tourist towns.","riskFlags":["restricted-platforms","tourist-wifi"]},
  {"iso2":"TJ","iso3":"TJK","nameEn":"Tajikistan","slug":"tajikistan","region":"APAC","languages":["tg","ru"],"currencyCode":"TJS","timeZonePrimary":"Asia/Dushanbe","internetNotes":"Limited internet market. Tcell and Megafon are carriers. Government controls internet infrastructure and imposes restrictions. Facebook and YouTube have been blocked periodically.","vpnNotes":"VPN use is common to bypass government blocks. Facebook, YouTube, and various websites have been blocked. Government monitors internet activity. Configure VPN before visiting.","paymentNotes":"TJS-based. Cash dominant. Very limited digital payment infrastructure. International card acceptance limited to Dushanbe hotels.","travelNotes":"Wi-Fi in Dushanbe hotels. Pamir Highway and mountain areas have very limited connectivity. Download offline maps and content before traveling.","riskFlags":["censorship","restricted-platforms","tourist-wifi"]}
];

const filePath = path.join(process.cwd(), "src", "data", "countries.json");
const existing = JSON.parse(fs.readFileSync(filePath, "utf-8"));
const existingIso2 = new Set(existing.map((c: { iso2: string }) => c.iso2));
const existingSlugs = new Set(existing.map((c: { slug: string }) => c.slug));

let added = 0;
for (const c of extra) {
  if (c.nameEn === "skip") continue;
  if (!existingIso2.has(c.iso2) && !existingSlugs.has(c.slug)) {
    existing.push(c);
    added++;
  }
}

fs.writeFileSync(filePath, JSON.stringify(existing, null, 2) + "\n");
console.log(`Added ${added}. Total: ${existing.length}`);
