import fs from "fs";
import path from "path";

const extra = [
  {"iso2":"BE","iso3":"BEL","nameEn":"Belgium","slug":"belgium","region":"Europe","languages":["nl","fr","de"],"currencyCode":"EUR","timeZonePrimary":"Europe/Brussels","internetNotes":"Excellent broadband infrastructure. Proximus, Telenet, and Orange are providers. Brussels hosts EU institutions with world-class connectivity and growing fiber deployment.","vpnNotes":"VPNs are fully legal in Belgium. EU capital with strong GDPR enforcement. High VPN adoption among EU institution workers, diplomats, and international community.","paymentNotes":"Euro-based. Card payments dominant. Bancontact is the local payment system. International payment methods widely accepted for all online services.","travelNotes":"Excellent Wi-Fi in Brussels, Antwerp, and Ghent. EU quarter particularly well-connected. SNCB/NMBS trains offer Wi-Fi on IC services.","riskFlags":["tourist-wifi"]},
  {"iso2":"AT","iso3":"AUT","nameEn":"Austria","slug":"austria","region":"Europe","languages":["de"],"currencyCode":"EUR","timeZonePrimary":"Europe/Vienna","internetNotes":"Good broadband. A1, Magenta, and Drei are providers. Fiber expanding in Vienna and major cities. Strong GDPR enforcement through Austrian DSB authority.","vpnNotes":"VPNs are fully legal in Austria. Strong privacy culture and active GDPR enforcement. Vienna's growing tech scene drives VPN adoption among professionals.","paymentNotes":"Euro-based. Card payments common. eps online banking transfers popular domestically. International payment methods accepted for online VPN purchases.","travelNotes":"Good Wi-Fi in Vienna hotels and cafes. Ski resorts generally connected. Alpine areas may have limited coverage. ÖBB Railjet trains offer Wi-Fi.","riskFlags":["tourist-wifi"]},
  {"iso2":"NO","iso3":"NOR","nameEn":"Norway","slug":"norway","region":"Europe","languages":["no","en"],"currencyCode":"NOK","timeZonePrimary":"Europe/Oslo","internetNotes":"Excellent infrastructure funded by oil wealth. Telenor, Telia, and Ice are providers. High speeds even in remote areas. Among the most connected countries globally.","vpnNotes":"VPNs are fully legal. Strong Scandinavian privacy traditions. Nearly cashless society increases importance of digital privacy. Vipps dominant for payments.","paymentNotes":"NOK-based. Vipps mobile payments dominant. Nearly cashless. Cards and contactless universal. International payment methods accepted everywhere.","travelNotes":"Excellent Wi-Fi in hotels, cafes, and public spaces throughout Norway. Even remote fjord communities have decent connectivity. Very well-connected nation.","riskFlags":["tourist-wifi"]},
  {"iso2":"GQ","iso3":"GNQ","nameEn":"Equatorial Guinea","slug":"equatorial-guinea","region":"Africa","languages":["es","fr","pt"],"currencyCode":"XAF","timeZonePrimary":"Africa/Malabo","internetNotes":"Limited internet infrastructure. GETESA is the main provider. Coverage concentrated in Malabo and Bata. Oil wealth hasn't translated to widespread internet access.","vpnNotes":"VPNs are legal but the government monitors internet content. Limited internet freedom. VPN useful for accessing unrestricted content and communication.","paymentNotes":"XAF (CFA franc) based. Cash dominant. Very limited card acceptance. International payment methods needed for online purchases. Prepay before visiting.","travelNotes":"Wi-Fi in major hotels in Malabo and Bata. Very limited coverage outside main cities. One of Africa's least connected countries despite oil wealth.","riskFlags":["restricted-platforms","tourist-wifi"]},
  {"iso2":"CF","iso3":"CAF","nameEn":"Central African Republic","slug":"central-african-republic","region":"Africa","languages":["fr","sg"],"currencyCode":"XAF","timeZonePrimary":"Africa/Bangui","internetNotes":"Extremely limited internet infrastructure. Telecel and Orange are carriers. Coverage mainly in Bangui. One of the least connected countries globally.","vpnNotes":"VPNs are legal but internet access itself is very limited. Mobile internet is the primary access method. Infrastructure challenges are more pressing than censorship.","paymentNotes":"XAF (CFA franc) based. Cash dominant. No significant card acceptance. International payment infrastructure essentially nonexistent locally.","travelNotes":"Very limited Wi-Fi even in Bangui hotels. Travel advisories in effect. Internet access should not be expected outside the capital.","riskFlags":["tourist-wifi"]},
  {"iso2":"TD","iso3":"TCD","nameEn":"Chad","slug":"chad","region":"Africa","languages":["fr","ar"],"currencyCode":"XAF","timeZonePrimary":"Africa/Ndjamena","internetNotes":"Very limited internet infrastructure. Tigo and Airtel are carriers. Coverage mainly in N'Djamena. Government has imposed internet shutdowns during political events.","vpnNotes":"VPN use is common during internet restrictions. Government has blocked social media and imposed full internet shutdowns. VPN essential during political tensions.","paymentNotes":"XAF (CFA franc) based. Cash dominant. No significant card acceptance outside major hotels. Prepay for all digital services before visiting.","travelNotes":"Limited Wi-Fi in N'Djamena hotels. Saharan and rural areas have no connectivity. Internet shutdowns can occur without warning during political events.","riskFlags":["censorship","restricted-platforms","tourist-wifi"]},
  {"iso2":"NE","iso3":"NER","nameEn":"Niger","slug":"niger","region":"Africa","languages":["fr"],"currencyCode":"XOF","timeZonePrimary":"Africa/Niamey","internetNotes":"Limited internet market. Airtel and Orange are carriers. Coverage mainly in Niamey. Saharan and rural areas have very limited or no connectivity.","vpnNotes":"VPNs are legal but internet access is very limited. Government has restricted social media during political events. VPN useful during restrictions.","paymentNotes":"XOF (CFA franc) based. Cash dominant. Mobile money growing via Airtel Money. Very limited international payment infrastructure.","travelNotes":"Limited Wi-Fi in Niamey hotels. Desert regions completely offline. One of the least connected countries in West Africa. Download everything offline.","riskFlags":["restricted-platforms","tourist-wifi"]},
  {"iso2":"BF","iso3":"BFA","nameEn":"Burkina Faso","slug":"burkina-faso","region":"Africa","languages":["fr"],"currencyCode":"XOF","timeZonePrimary":"Africa/Ouagadougou","internetNotes":"Limited internet market. Orange and Telecel are carriers. Coverage in Ouagadougou. Government has suspended social media during political transitions.","vpnNotes":"VPN use increased during social media suspensions. Government has blocked Facebook, WhatsApp, and other platforms. VPN essential during political tensions.","paymentNotes":"XOF (CFA franc) based. Orange Money growing. Cash dominant. Very limited international card acceptance.","travelNotes":"Wi-Fi in some Ouagadougou hotels. Very limited coverage outside the capital. Security situation affects both travel and connectivity.","riskFlags":["censorship","restricted-platforms","tourist-wifi"]},
  {"iso2":"SL","iso3":"SLE","nameEn":"Sierra Leone","slug":"sierra-leone","region":"Africa","languages":["en"],"currencyCode":"SLE","timeZonePrimary":"Africa/Freetown","internetNotes":"Growing mobile internet market. Africell, Orange, and Sierratel are carriers. Coverage in Freetown. Rural areas have limited connectivity.","vpnNotes":"VPNs are legal in Sierra Leone. Government has restricted internet access during elections. English-speaking with growing digital adoption.","paymentNotes":"SLE-based. Cash dominant. Orange Money growing. Very limited international card acceptance outside Freetown hotels.","travelNotes":"Wi-Fi in Freetown hotels. Beach areas like Tokeh may have limited connectivity. Rural areas largely offline. Mobile data from Africell recommended.","riskFlags":["tourist-wifi","restricted-platforms"]},
  {"iso2":"LR","iso3":"LBR","nameEn":"Liberia","slug":"liberia","region":"Africa","languages":["en"],"currencyCode":"LRD","timeZonePrimary":"Africa/Monrovia","internetNotes":"Limited internet infrastructure. Lonestar Cell MTN and Orange are carriers. Coverage in Monrovia. USD used alongside local currency due to historical ties.","vpnNotes":"VPNs are legal in Liberia. No significant restrictions on internet access. English-speaking with growing mobile internet adoption.","paymentNotes":"LRD and USD both used. Cash dominant. Very limited card acceptance. Mobile money growing via MTN MoMo and Orange Money.","travelNotes":"Wi-Fi in some Monrovia hotels. Very limited coverage outside the capital. Roads and infrastructure challenges affect connectivity.","riskFlags":["tourist-wifi"]}
];

const filePath = path.join(process.cwd(), "src", "data", "countries.json");
const existing = JSON.parse(fs.readFileSync(filePath, "utf-8"));
const existingIso2 = new Set(existing.map((c: { iso2: string }) => c.iso2));
const existingSlugs = new Set(existing.map((c: { slug: string }) => c.slug));

let added = 0;
for (const c of extra) {
  if (!existingIso2.has(c.iso2) && !existingSlugs.has(c.slug)) {
    existing.push(c);
    added++;
  }
}

fs.writeFileSync(filePath, JSON.stringify(existing, null, 2) + "\n");
console.log(`Added ${added}. Total: ${existing.length}`);
