import fs from "fs";
import path from "path";

const extra = [
  {"iso2":"SM","iso3":"SMR","nameEn":"San Marino","slug":"san-marino","region":"Europe","languages":["it"],"currencyCode":"EUR","timeZonePrimary":"Europe/San_Marino","internetNotes":"Good infrastructure. Uses Italian telecom networks. Compact microstate with comprehensive coverage.","vpnNotes":"VPNs fully legal. Italian telecom infrastructure and regulations apply. Open internet access.","paymentNotes":"Euro-based. Card payments accepted. Italian payment systems work. International methods accepted online.","travelNotes":"Covered by Italian networks. Good Wi-Fi in hotels and restaurants throughout this tiny republic.","riskFlags":["tourist-wifi"]},
  {"iso2":"VA","iso3":"VAT","nameEn":"Vatican City","slug":"vatican-city","region":"Europe","languages":["it","la"],"currencyCode":"EUR","timeZonePrimary":"Europe/Vatican","internetNotes":"Uses Italian telecom infrastructure. Vatican has its own .va domain. Compact territory with good Wi-Fi in visitor areas.","vpnNotes":"VPNs fully legal. Italian networks available. World's smallest state with comprehensive connectivity.","paymentNotes":"Euro-based. Card payments accepted in Vatican Museums and shops. Italian payment infrastructure.","travelNotes":"Vatican Museums and St. Peter's area have Wi-Fi. Italian mobile coverage extends throughout.","riskFlags":["tourist-wifi"]},
  {"iso2":"XK","iso3":"XKX","nameEn":"Kosovo","slug":"kosovo","region":"Europe","languages":["sq","sr"],"currencyCode":"EUR","timeZonePrimary":"Europe/Belgrade","internetNotes":"Growing internet infrastructure. IPKO and Vala are major providers. Pristina has good connectivity with improving broadband speeds.","vpnNotes":"VPNs fully legal. No restrictions on internet access. Growing IT sector in Pristina drives adoption.","paymentNotes":"Euro-based. Card payments growing in Pristina. Cash widely used. International methods available online.","travelNotes":"Good Wi-Fi in Pristina hotels and cafes. Coverage in major towns. Rural areas have limited connectivity.","riskFlags":["tourist-wifi"]},
  {"iso2":"AG","iso3":"ATG","nameEn":"Antigua and Barbuda","slug":"antigua-and-barbuda","region":"Americas","languages":["en"],"currencyCode":"XCD","timeZonePrimary":"America/Antigua","internetNotes":"Decent for Caribbean. FLOW and Digicel provide mobile and broadband. Coverage on both islands. Growing digital nomad infrastructure.","vpnNotes":"VPNs fully legal. English-speaking with open internet. No restrictions on VPN use.","paymentNotes":"XCD-based. USD accepted. Card payments in tourist areas. International payment methods work online.","travelNotes":"Good Wi-Fi in resort hotels. Antigua better connected than Barbuda. Beach areas generally covered.","riskFlags":["tourist-wifi"]},
  {"iso2":"DM","iso3":"DMA","nameEn":"Dominica","slug":"dominica","region":"Americas","languages":["en"],"currencyCode":"XCD","timeZonePrimary":"America/Dominica","internetNotes":"Basic infrastructure. FLOW and Digicel are providers. Coverage in Roseau. Mountain and rainforest areas have limited connectivity.","vpnNotes":"VPNs fully legal. Nature-focused island with open internet. No restrictions.","paymentNotes":"XCD-based. Cash dominant. Card acceptance in larger establishments. International methods for online purchases.","travelNotes":"Wi-Fi in Roseau hotels. Eco-lodges and rainforest areas may have satellite-only or no connectivity.","riskFlags":["tourist-wifi"]},
  {"iso2":"GD","iso3":"GRD","nameEn":"Grenada","slug":"grenada","region":"Americas","languages":["en"],"currencyCode":"XCD","timeZonePrimary":"America/Grenada","internetNotes":"Basic but functional. FLOW and Digicel provide coverage. St. George's and tourist areas connected. Spice island infrastructure.","vpnNotes":"VPNs fully legal. English-speaking with open internet access. No restrictions on VPN use.","paymentNotes":"XCD-based. USD accepted in tourist areas. Card payments at hotels and restaurants.","travelNotes":"Wi-Fi in St. George's hotels and Grand Anse beach resorts. Rural areas have limited coverage.","riskFlags":["tourist-wifi"]},
  {"iso2":"KN","iso3":"KNA","nameEn":"Saint Kitts and Nevis","slug":"saint-kitts-and-nevis","region":"Americas","languages":["en"],"currencyCode":"XCD","timeZonePrimary":"America/St_Kitts","internetNotes":"Decent for a small Caribbean nation. FLOW and Digicel are providers. Both islands have coverage. CBI program attracts tech-savvy residents.","vpnNotes":"VPNs fully legal. English-speaking with open internet. Citizenship by Investment community drives digital adoption.","paymentNotes":"XCD-based. USD accepted. Card payments in tourist areas. International payment methods work.","travelNotes":"Good Wi-Fi in Basseterre hotels and resorts. Both islands have decent coverage.","riskFlags":["tourist-wifi"]},
  {"iso2":"LC","iso3":"LCA","nameEn":"Saint Lucia","slug":"saint-lucia","region":"Americas","languages":["en"],"currencyCode":"XCD","timeZonePrimary":"America/St_Lucia","internetNotes":"Decent infrastructure. FLOW and Digicel are providers. Good coverage in Castries and resort areas. The Pitons area connected.","vpnNotes":"VPNs fully legal. Popular tourist destination with English-speaking open internet.","paymentNotes":"XCD-based. USD accepted in tourist areas. Card payments at resorts and major businesses.","travelNotes":"Good Wi-Fi in resort hotels. Castries and Rodney Bay well-connected. Rural areas more limited.","riskFlags":["tourist-wifi"]},
  {"iso2":"VC","iso3":"VCT","nameEn":"Saint Vincent and the Grenadines","slug":"saint-vincent-grenadines","region":"Americas","languages":["en"],"currencyCode":"XCD","timeZonePrimary":"America/St_Vincent","internetNotes":"Basic infrastructure. FLOW and Digicel are providers. Coverage on St. Vincent. Grenadine islands have more limited connectivity.","vpnNotes":"VPNs fully legal. English-speaking with open internet. No restrictions on VPN use.","paymentNotes":"XCD-based. Cash dominant. Card payments at larger hotels. International payment methods online.","travelNotes":"Wi-Fi in Kingstown hotels. Bequia and Mustique have resort Wi-Fi. Smaller Grenadines may have limited coverage.","riskFlags":["tourist-wifi"]},
  {"iso2":"SX","iso3":"SXM","nameEn":"Sint Maarten","slug":"sint-maarten","region":"Americas","languages":["nl","en"],"currencyCode":"ANG","timeZonePrimary":"America/Lower_Princes","internetNotes":"Good infrastructure for a small Caribbean territory. TelEm and UTS are providers. Tourist-driven economy supports good connectivity.","vpnNotes":"VPNs fully legal. Dutch territory with open internet. Shared island with French Saint-Martin.","paymentNotes":"ANG-based. USD widely accepted. Card payments common in tourist areas. International methods work.","travelNotes":"Good Wi-Fi in Philipsburg hotels and beach bars. Maho Beach area famous and well-connected. Small island with good coverage.","riskFlags":["tourist-wifi"]},
  {"iso2":"MF","iso3":"MAF","nameEn":"Saint Martin","slug":"saint-martin","region":"Americas","languages":["fr","en"],"currencyCode":"EUR","timeZonePrimary":"America/Marigot","internetNotes":"Good infrastructure. French side uses Orange and SFR networks. Euro-based economy. Good connectivity in Marigot and tourist areas.","vpnNotes":"VPNs fully legal. French territory with open internet. French digital rights apply.","paymentNotes":"Euro-based. Card payments accepted. French payment systems work. International methods available.","travelNotes":"Good Wi-Fi in hotels and restaurants. French side generally well-connected. Shared island with Dutch Sint Maarten.","riskFlags":["tourist-wifi"]}
];

const filePath = path.join(process.cwd(), "src", "data", "countries.json");
const existing = JSON.parse(fs.readFileSync(filePath, "utf-8"));
const existingIso2 = new Set(existing.map((c: { iso2: string }) => c.iso2));
const existingSlugs = new Set(existing.map((c: { slug: string }) => c.slug));

let added = 0;
for (const c of extra) {
  if (!existingIso2.has(c.iso2) && !existingSlugs.has(c.slug)) {
    existing.push(c);
    added++;
  }
}

fs.writeFileSync(filePath, JSON.stringify(existing, null, 2) + "\n");
console.log(`Added ${added}. Total: ${existing.length}`);
