import fs from "fs";
import path from "path";

const extra = [
  {"iso2":"PG","iso3":"PNG","nameEn":"Papua New Guinea","slug":"papua-new-guinea","region":"APAC","languages":["en","tpi","ho"],"currencyCode":"PGK","timeZonePrimary":"Pacific/Port_Moresby","internetNotes":"Limited infrastructure. Digicel and Telikom are carriers. Coverage in Port Moresby. Highlands and remote areas have very limited connectivity.","vpnNotes":"VPNs are legal. No significant internet restrictions. Infrastructure is the main challenge rather than censorship.","paymentNotes":"PGK-based. Cash dominant. Very limited card acceptance. International payment methods for online purchases only.","travelNotes":"Wi-Fi in Port Moresby hotels. Very limited outside the capital. Highland areas and islands largely offline.","riskFlags":["tourist-wifi"]},
  {"iso2":"WS","iso3":"WSM","nameEn":"Samoa","slug":"samoa","region":"APAC","languages":["sm","en"],"currencyCode":"WST","timeZonePrimary":"Pacific/Apia","internetNotes":"Basic but improving internet. Digicel and Vodafone are providers. Submarine cable improved speeds. Coverage mainly in Apia area.","vpnNotes":"VPNs are legal. No internet restrictions. Small island nation with open internet policy.","paymentNotes":"WST-based. Cash dominant. Card acceptance in Apia hotels and major businesses. International payment methods for online use.","travelNotes":"Wi-Fi in Apia hotels and some beach resorts. Remote areas and outer islands have limited connectivity.","riskFlags":["tourist-wifi"]},
  {"iso2":"TO","iso3":"TON","nameEn":"Tonga","slug":"tonga","region":"APAC","languages":["to","en"],"currencyCode":"TOP","timeZonePrimary":"Pacific/Tongatapu","internetNotes":"Limited infrastructure. Tonga Communications Corporation and Digicel are providers. Submarine cable providing improved connectivity since repair after 2022 eruption.","vpnNotes":"VPNs are legal. No significant internet restrictions. Submarine cable vulnerability demonstrated during 2022 volcanic eruption.","paymentNotes":"TOP-based. Cash dominant. Limited card acceptance in Nuku'alofa. International payment methods for online services.","travelNotes":"Wi-Fi in Nuku'alofa hotels. Outer islands have very limited connectivity. Internet can be disrupted by natural events.","riskFlags":["tourist-wifi"]},
  {"iso2":"VU","iso3":"VUT","nameEn":"Vanuatu","slug":"vanuatu","region":"APAC","languages":["bi","en","fr"],"currencyCode":"VUV","timeZonePrimary":"Pacific/Efate","internetNotes":"Basic infrastructure. Digicel and Vodafone are providers. Coverage in Port Vila. Outer islands have limited connectivity.","vpnNotes":"VPNs are legal. No internet restrictions. Small Pacific nation with open internet access.","paymentNotes":"VUV-based. Cash dominant. Card acceptance in Port Vila tourist areas. International payment methods available online.","travelNotes":"Wi-Fi in Port Vila hotels and resorts. Outer islands have limited or satellite-only connectivity.","riskFlags":["tourist-wifi"]},
  {"iso2":"SB","iso3":"SLB","nameEn":"Solomon Islands","slug":"solomon-islands","region":"APAC","languages":["en"],"currencyCode":"SBD","timeZonePrimary":"Pacific/Guadalcanal","internetNotes":"Very limited infrastructure. Our Telekom is the main provider. Coverage mainly in Honiara. Outer islands have minimal connectivity.","vpnNotes":"VPNs are legal. No internet restrictions. Infrastructure limitations are the main connectivity challenge.","paymentNotes":"SBD-based. Cash dominant. Very limited card acceptance. International payment methods needed for online services.","travelNotes":"Wi-Fi in Honiara hotels. Diving resorts may have satellite connectivity. Very limited coverage outside the capital.","riskFlags":["tourist-wifi"]},
  {"iso2":"TM","iso3":"TKM","nameEn":"Turkmenistan","slug":"turkmenistan","region":"APAC","languages":["tk","ru"],"currencyCode":"TMT","timeZonePrimary":"Asia/Ashgabat","internetNotes":"One of the most restricted internet environments globally. Turkmentelecom is the sole provider. Government controls all internet access. Extremely slow and expensive.","vpnNotes":"VPN use is technically illegal but widely practiced. The government blocks VPN services aggressively. Internet access is severely restricted and monitored. One of the most censored countries in the world.","paymentNotes":"TMT-based. Cash dominant. No international payment infrastructure. All services must be prepaid before entering.","travelNotes":"Extremely limited and slow internet even in Ashgabat. VPN may not work reliably. Do not rely on internet access. One of the most connected-challenged countries.","riskFlags":["censorship","restricted-platforms","tourist-wifi"]},
  {"iso2":"SY","iso3":"SYR","nameEn":"Syria","slug":"syria","region":"Middle East","languages":["ar"],"currencyCode":"SYP","timeZonePrimary":"Asia/Damascus","internetNotes":"Severely damaged infrastructure. SyriaTel and MTN Syria are carriers. Internet access is limited and monitored. Different areas under different control have varying connectivity.","vpnNotes":"VPN use is widespread to bypass censorship. Government monitors internet extensively. VPN essential but reliability varies by region and controlling authority. Configure before entering.","paymentNotes":"SYP-based. Cash only. International payment infrastructure nonexistent. All services must be prepaid. Sanctions may affect digital service access.","travelNotes":"Very limited internet. Damascus has basic connectivity. Conflict-affected areas may have no telecommunications. Active travel warnings.","riskFlags":["censorship","restricted-platforms","tourist-wifi"]},
  {"iso2":"KP","iso3":"PRK","nameEn":"North Korea","slug":"north-korea","region":"APAC","languages":["ko"],"currencyCode":"KPW","timeZonePrimary":"Asia/Pyongyang","internetNotes":"No public internet access. Only a domestic intranet (Kwangmyong) exists. Foreign visitors may access limited internet through 3G from Koryolink but it is monitored.","vpnNotes":"VPN use is essentially impossible for citizens. Foreign visitors with 3G access may use VPNs but all traffic is monitored. One of the most isolated internet environments on Earth.","paymentNotes":"KPW-based. Completely cash-based economy. No international payment infrastructure. Everything must be arranged through state tourism agency.","travelNotes":"No public internet or Wi-Fi. Foreign tourists may get monitored 3G through Koryolink. Do not expect any internet access. All tourism is state-controlled.","riskFlags":["censorship","restricted-platforms","tourist-wifi"]},
  {"iso2":"IR","iso3":"IRN","nameEn":"Iran","slug":"iran","region":"Middle East","languages":["fa"],"currencyCode":"IRR","timeZonePrimary":"Asia/Tehran","internetNotes":"Extensive internet infrastructure but heavily censored. Government controls the National Information Network. DPI and throttling used extensively. Internet shutdowns during protests.","vpnNotes":"VPN use is extremely widespread in Iran — estimated 40-80% of internet users use VPNs. The government blocks VPN services aggressively using DPI but users constantly find workarounds. Configure multiple VPN options before entering.","paymentNotes":"IRR-based. International payment infrastructure blocked by sanctions. Cash and domestic payment systems only. Prepay everything before entering Iran.","travelNotes":"Wi-Fi available in Tehran and Isfahan hotels. Internet is heavily filtered. VPN essential but unreliable during crackdowns. Social media, many news sites, and Western services blocked.","riskFlags":["censorship","restricted-platforms","tourist-wifi"]},
  {"iso2":"VE","iso3":"VEN","nameEn":"Venezuela","slug":"venezuela","region":"Americas","languages":["es"],"currencyCode":"VES","timeZonePrimary":"America/Caracas","internetNotes":"Deteriorating infrastructure. CANTV (state-owned) is the main broadband provider. Frequent outages. Private mobile operators Movistar, Digitel, and Movilnet offer 4G in cities.","vpnNotes":"VPN use is legal and growing. Government has blocked news sites and social media during political events. VPN essential for accessing independent media and communication.","paymentNotes":"VES-based but highly volatile. USD widely used in practice. International payment methods limited by sanctions. Cash and crypto increasingly used.","travelNotes":"Wi-Fi in Caracas and major city hotels. Infrastructure deteriorating. Power outages affect connectivity. Download offline content before traveling.","riskFlags":["censorship","restricted-platforms","tourist-wifi"]}
];

const filePath = path.join(process.cwd(), "src", "data", "countries.json");
const existing = JSON.parse(fs.readFileSync(filePath, "utf-8"));
const existingIso2 = new Set(existing.map((c: { iso2: string }) => c.iso2));
const existingSlugs = new Set(existing.map((c: { slug: string }) => c.slug));

let added = 0;
for (const c of extra) {
  if (!existingIso2.has(c.iso2) && !existingSlugs.has(c.slug)) {
    existing.push(c);
    added++;
  }
}

fs.writeFileSync(filePath, JSON.stringify(existing, null, 2) + "\n");
console.log(`Added ${added}. Total: ${existing.length}`);
