import fs from "fs";
import path from "path";

const extra = [
  {"iso2":"AL","iso3":"ALB","nameEn":"Albania","slug":"albania","region":"Europe","languages":["sq"],"currencyCode":"ALL","timeZonePrimary":"Europe/Tirane","internetNotes":"Improving broadband infrastructure with fiber expanding in Tirana and major cities. Albanian Telecom, Vodafone, and One are major providers offering increasingly competitive pricing and speeds.","vpnNotes":"VPNs are fully legal and unrestricted in Albania. The country has a relatively open internet environment with no government restrictions on VPN usage or significant content blocking.","paymentNotes":"ALL-based. Card payments growing in Tirana but cash still common elsewhere. International payment methods available online for VPN subscriptions and international services.","travelNotes":"Good Wi-Fi in Tirana hotels and cafes. Coastal tourist areas like Saranda and Vlora generally connected. Rural areas may have limited coverage but mobile data is affordable.","riskFlags":["tourist-wifi"]},
  {"iso2":"ME","iso3":"MNE","nameEn":"Montenegro","slug":"montenegro","region":"Europe","languages":["sr","en"],"currencyCode":"EUR","timeZonePrimary":"Europe/Podgorica","internetNotes":"Decent broadband coverage for a small country. Crnogorski Telekom and m:tel are major providers. Internet quality good in Podgorica and coastal areas with improving fiber deployment.","vpnNotes":"VPNs are fully legal in Montenegro. No restrictions on internet access. The growing tourism and remote work scene drives VPN adoption among visitors and digital nomads.","paymentNotes":"Euro-based (unilateral adoption). Card payments common in tourist areas. Cash still important in smaller towns. International payment methods work well for online purchases.","travelNotes":"Good Wi-Fi in Budva, Kotor, and Podgorica hotels and cafes. Coastal tourist areas well-connected during summer season. Mountain areas may have limited coverage.","riskFlags":["tourist-wifi"]},
  {"iso2":"XK","iso3":"XKX","nameEn":"Kosovo","slug":"kosovo","region":"Europe","languages":["sq","sr"],"currencyCode":"EUR","timeZonePrimary":"Europe/Belgrade","internetNotes":"Growing internet infrastructure. IPKO and Vala are major providers. Pristina has good connectivity with improving broadband speeds across the country.","vpnNotes":"VPNs are fully legal in Kosovo. No restrictions on internet access. Growing IT sector in Pristina drives technology adoption including VPN usage.","paymentNotes":"Euro-based. Card payments growing in Pristina. Cash still widely used. International payment methods available for online VPN purchases.","travelNotes":"Good Wi-Fi in Pristina hotels and cafes. Coverage adequate in major towns. Rural areas may have limited connectivity but mobile data coverage is growing.","riskFlags":["tourist-wifi"]},
  {"iso2":"MD","iso3":"MDA","nameEn":"Moldova","slug":"moldova","region":"Europe","languages":["ro","ru"],"currencyCode":"MDL","timeZonePrimary":"Europe/Chisinau","internetNotes":"Surprisingly fast and affordable internet. Moldtelecom, Orange, and Starnet are providers. Moldova has some of the cheapest broadband in Europe with competitive speeds.","vpnNotes":"VPNs are fully legal in Moldova. Growing IT outsourcing sector in Chisinau drives adoption. No government restrictions on VPN use or internet access.","paymentNotes":"MDL-based. Card payments growing but cash still common. International payment methods available online. Affordable internet and VPN costs.","travelNotes":"Good Wi-Fi in Chisinau hotels and cafes. Wine region tourism growing. Rural areas may have limited coverage. Very affordable mobile data plans available.","riskFlags":["tourist-wifi"]},
  {"iso2":"BY","iso3":"BLR","nameEn":"Belarus","slug":"belarus","region":"Europe","languages":["be","ru"],"currencyCode":"BYN","timeZonePrimary":"Europe/Minsk","internetNotes":"Decent urban coverage through Beltelecom. Government controls internet infrastructure and has imposed shutdowns during political protests. Internet monitoring is extensive.","vpnNotes":"VPN use is legal but the government has periodically blocked VPN services during political unrest. Many Belarusians use VPNs to access independent media blocked by the government. Configure VPN before entering the country.","paymentNotes":"BYN-based. International payment methods may be restricted due to sanctions. Card payments work in major businesses but cash is important. Prepay for VPN subscriptions before visiting.","travelNotes":"Wi-Fi available in Minsk hotels and cafes. Coverage adequate in major cities. VPN recommended for accessing independent news and social media during politically sensitive periods.","riskFlags":["censorship","restricted-platforms","tourist-wifi"]},
  {"iso2":"BN","iso3":"BRN","nameEn":"Brunei","slug":"brunei","region":"APAC","languages":["ms","en"],"currencyCode":"BND","timeZonePrimary":"Asia/Brunei","internetNotes":"Decent broadband infrastructure for a small nation. DST and Progresif are the main providers. Internet speeds improving with fiber deployment in Bandar Seri Begawan.","vpnNotes":"VPNs are legal for personal use in Brunei. Some content is filtered by the government including adult content and gambling sites. VPN use is common among expats and tech-savvy residents.","paymentNotes":"BND-based (pegged to SGD). Card payments accepted in major establishments. Cash still widely used. International payment methods available for online VPN purchases.","travelNotes":"Good Wi-Fi in hotels in Bandar Seri Begawan. Coverage limited outside the capital. VPN useful for accessing some filtered content during your stay.","riskFlags":["restricted-platforms","tourist-wifi"]},
  {"iso2":"LA","iso3":"LAO","nameEn":"Laos","slug":"laos","region":"APAC","languages":["lo"],"currencyCode":"LAK","timeZonePrimary":"Asia/Vientiane","internetNotes":"Growing internet market primarily mobile-based. Unitel, ETL, and Lao Telecom are providers. Good coverage in Vientiane and Luang Prabang. Rural areas have limited connectivity.","vpnNotes":"VPNs are legal in Laos. Government monitors internet content but VPN use is not restricted. Used by tourists and the growing expat community in Vientiane.","paymentNotes":"LAK-based. Cash dominant. Card payments limited to major hotels and restaurants. International payment methods needed for online VPN subscriptions.","travelNotes":"Wi-Fi in hotels and guesthouses in Vientiane and Luang Prabang. Tourist cafes generally have Wi-Fi. Rural and remote areas have very limited connectivity.","riskFlags":["tourist-wifi","restricted-platforms"]},
  {"iso2":"PY","iso3":"PRY","nameEn":"Paraguay","slug":"paraguay","region":"Americas","languages":["es","gn"],"currencyCode":"PYG","timeZonePrimary":"America/Asuncion","internetNotes":"Growing internet market. Tigo, Personal, and Claro are major carriers. Good mobile coverage in Asuncion and major cities. Rural areas have limited broadband access.","vpnNotes":"VPNs are fully legal and unrestricted in Paraguay. Growing remote work community drives adoption. No government restrictions on VPN use or internet content.","paymentNotes":"PYG-based. Cash dominant. Card payments growing in Asuncion. International payment methods available online for VPN and subscription purchases.","travelNotes":"Wi-Fi in hotels and cafes in Asuncion. Coverage adequate in major cities. Rural areas and Chaco region have very limited connectivity.","riskFlags":["tourist-wifi"]},
  {"iso2":"BO","iso3":"BOL","nameEn":"Bolivia","slug":"bolivia","region":"Americas","languages":["es"],"currencyCode":"BOB","timeZonePrimary":"America/La_Paz","internetNotes":"Growing internet market. Entel, Tigo, and Viva are major carriers. Good coverage in La Paz, Cochabamba, and Santa Cruz. Rural and highland areas have limited connectivity.","vpnNotes":"VPNs are fully legal in Bolivia. No significant restrictions on internet access. Growing adoption among tech workers and remote professionals in major cities.","paymentNotes":"BOB-based. Cash dominant. Card payments growing in major cities. International payment methods available online for VPN subscriptions.","travelNotes":"Wi-Fi in hotels in La Paz, Cochabamba, and Santa Cruz. Tourist areas generally connected. Altitude and remote areas (Salar de Uyuni) may have no connectivity.","riskFlags":["tourist-wifi"]},
  {"iso2":"HN","iso3":"HND","nameEn":"Honduras","slug":"honduras","region":"Americas","languages":["es"],"currencyCode":"HNL","timeZonePrimary":"America/Tegucigalpa","internetNotes":"Growing mobile internet market. Tigo and Claro are the main carriers. Good coverage in Tegucigalpa and San Pedro Sula. Rural areas and Bay Islands have variable connectivity.","vpnNotes":"VPNs are fully legal in Honduras. No restrictions on internet access or VPN usage. Used by the growing digital community and tourists on the Bay Islands.","paymentNotes":"HNL-based. Cash widely used. Card payments accepted in larger businesses and tourist areas. International payment methods available for online purchases.","travelNotes":"Wi-Fi in hotels in Tegucigalpa and Roatan. Bay Islands tourist areas generally connected. Rural mainland areas may have limited or no Wi-Fi coverage.","riskFlags":["tourist-wifi"]},
  {"iso2":"SV","iso3":"SLV","nameEn":"El Salvador","slug":"el-salvador","region":"Americas","languages":["es"],"currencyCode":"USD","timeZonePrimary":"America/El_Salvador","internetNotes":"Decent coverage in urban areas. Tigo, Claro, and Movistar are providers. USD economy simplifies international transactions. Growing tech and Bitcoin adoption community.","vpnNotes":"VPNs are fully legal in El Salvador. The country's Bitcoin adoption and tech-forward stance means VPN use is well-understood and unrestricted.","paymentNotes":"USD-based, simplifying international payments significantly. Card payments accepted in urban areas and tourist spots. Bitcoin accepted in some establishments as legal tender.","travelNotes":"Wi-Fi in hotels and cafes in San Salvador. El Tunco beach and tourist areas generally connected. Rural areas may have limited coverage. USD makes VPN purchases simple.","riskFlags":["tourist-wifi"]},
  {"iso2":"NI","iso3":"NIC","nameEn":"Nicaragua","slug":"nicaragua","region":"Americas","languages":["es"],"currencyCode":"NIO","timeZonePrimary":"America/Managua","internetNotes":"Growing internet market. Claro and Movistar are the main carriers. Coverage improving in Managua and major cities. Rural areas and Caribbean coast have limited connectivity.","vpnNotes":"VPNs are legal in Nicaragua. Government has occasionally restricted social media access during political events but VPN use itself is not restricted.","paymentNotes":"NIO-based. Cash widely used. Card payments accepted in tourist areas and larger businesses. International payment methods available for online purchases.","travelNotes":"Wi-Fi in hotels in Managua, Granada, and San Juan del Sur. Tourist areas generally connected. Caribbean coast and rural areas have very limited connectivity.","riskFlags":["tourist-wifi","restricted-platforms"]},
  {"iso2":"CU","iso3":"CUB","nameEn":"Cuba","slug":"cuba","region":"Americas","languages":["es"],"currencyCode":"CUP","timeZonePrimary":"America/Havana","internetNotes":"One of the least connected countries in the Americas. ETECSA is the sole provider. Internet access was severely restricted until recent years. Mobile data available but expensive and slow.","vpnNotes":"VPN use is common among Cubans to bypass censorship but exists in a legal gray area. The government censors content and monitors internet usage. Configure your VPN before traveling to Cuba.","paymentNotes":"CUP-based. International payment infrastructure very limited. Cash (CUP and sometimes USD/EUR) essential. Prepay for VPN before arrival as online payments are difficult within Cuba.","travelNotes":"Hotel Wi-Fi available in major cities but slow and expensive. Public Wi-Fi hotspots exist in parks (ETECSA). Internet access is a challenge. Download everything offline before arrival.","riskFlags":["censorship","restricted-platforms","tourist-wifi"]},
  {"iso2":"MW","iso3":"MWI","nameEn":"Malawi","slug":"malawi","region":"Africa","languages":["en","ny"],"currencyCode":"MWK","timeZonePrimary":"Africa/Blantyre","internetNotes":"Growing mobile internet market. TNM and Airtel are the main carriers. Coverage concentrated in Lilongwe and Blantyre. Internet speeds are among the slowest in Africa.","vpnNotes":"VPNs are legal in Malawi. No significant restrictions on internet access. Government has occasionally throttled social media during elections but VPN use is not restricted.","paymentNotes":"MWK-based. Cash dominant. Mobile money through Airtel Money and TNM Mpamba growing. International card acceptance very limited. Prepay for VPN services.","travelNotes":"Wi-Fi in hotels in Lilongwe and Blantyre. Lake Malawi lodges increasingly offer connectivity. Rural areas have very limited or no internet access.","riskFlags":["tourist-wifi"]},
  {"iso2":"ZM","iso3":"ZMB","nameEn":"Zambia","slug":"zambia","region":"Africa","languages":["en"],"currencyCode":"ZMW","timeZonePrimary":"Africa/Lusaka","internetNotes":"Growing internet market. MTN, Airtel, and Zamtel are major carriers. Good 4G coverage in Lusaka and Copperbelt. Rural areas have limited connectivity but mobile coverage expanding.","vpnNotes":"VPNs are legal in Zambia. Government has occasionally restricted social media during political events. VPN use grew during the 2021 election period when social media was throttled.","paymentNotes":"ZMW-based. Mobile money (MTN MoMo, Airtel Money) growing rapidly. Cash dominant. International card acceptance limited to major hotels and businesses.","travelNotes":"Wi-Fi in Lusaka hotels and lodges. Victoria Falls area has decent connectivity. National parks and safari areas have limited or satellite-only internet.","riskFlags":["tourist-wifi","restricted-platforms"]},
  {"iso2":"ZW","iso3":"ZWE","nameEn":"Zimbabwe","slug":"zimbabwe","region":"Africa","languages":["en","sn","nd"],"currencyCode":"ZWL","timeZonePrimary":"Africa/Harare","internetNotes":"Challenging internet landscape. Econet, NetOne, and Telecel are carriers. Government has imposed internet shutdowns during protests. Data costs are high relative to incomes.","vpnNotes":"VPN use is widespread in Zimbabwe, especially during government-imposed internet shutdowns. The government has blocked social media multiple times. VPNs are commonly used to access blocked services.","paymentNotes":"Multi-currency system (USD, ZWL, ZAR). Mobile money via EcoCash dominant. Cash shortages common. International payment methods may be difficult. Prepay for VPN before visiting.","travelNotes":"Wi-Fi in hotels in Harare and Victoria Falls. Tourist lodges increasingly offer connectivity. Rural areas have very limited access. VPN recommended for accessing social media during shutdowns.","riskFlags":["censorship","restricted-platforms","tourist-wifi"]},
  {"iso2":"MZ","iso3":"MOZ","nameEn":"Mozambique","slug":"mozambique","region":"Africa","languages":["pt"],"currencyCode":"MZN","timeZonePrimary":"Africa/Maputo","internetNotes":"Growing mobile internet market. Vodacom, TMcel, and Movitel are carriers. Coverage concentrated in Maputo and major cities. Northern and rural areas have limited connectivity.","vpnNotes":"VPNs are legal in Mozambique. No significant restrictions on internet access. Growing mobile internet adoption driving increased awareness of online security.","paymentNotes":"MZN-based. Mobile money (M-Pesa via Vodacom) growing. Cash dominant. International card acceptance limited to major hotels and businesses in Maputo.","travelNotes":"Wi-Fi in hotels in Maputo and tourist areas. Beach resorts in Vilankulo and Tofo increasingly offer connectivity. Northern coast and interior have limited coverage.","riskFlags":["tourist-wifi"]},
  {"iso2":"CM","iso3":"CMR","nameEn":"Cameroon","slug":"cameroon","region":"Africa","languages":["fr","en"],"currencyCode":"XAF","timeZonePrimary":"Africa/Douala","internetNotes":"Growing internet market. MTN, Orange, and Nexttel are carriers. Government has imposed internet shutdowns in English-speaking regions. Good coverage in Douala and Yaounde.","vpnNotes":"VPN use is widespread in Cameroon, especially in English-speaking regions where the government imposed a months-long internet shutdown in 2017. VPNs are commonly used for access and privacy.","paymentNotes":"XAF (CFA franc) based. Orange Money and MTN MoMo mobile payments common. Cash widely used. International card acceptance limited outside major businesses.","travelNotes":"Wi-Fi in hotels in Douala and Yaounde. Tourist areas generally connected. English-speaking regions have experienced connectivity disruptions. Mobile data affordable.","riskFlags":["censorship","restricted-platforms","tourist-wifi"]},
  {"iso2":"CI","iso3":"CIV","nameEn":"Ivory Coast","slug":"ivory-coast","region":"Africa","languages":["fr"],"currencyCode":"XOF","timeZonePrimary":"Africa/Abidjan","internetNotes":"Growing internet infrastructure. MTN, Orange, and Moov are major carriers. Good mobile coverage in Abidjan with submarine cable connections improving speeds nationwide.","vpnNotes":"VPNs are legal in Ivory Coast. Government has occasionally restricted social media during political events. VPN use growing among the tech-savvy population in Abidjan.","paymentNotes":"XOF (CFA franc) based. Orange Money and MTN MoMo mobile payments dominant. Cash widely used. International card acceptance limited to major businesses.","travelNotes":"Wi-Fi in hotels and cafes in Abidjan. Coverage adequate in major cities. Rural areas have limited connectivity. Prepaid mobile data SIM cards are affordable.","riskFlags":["tourist-wifi","restricted-platforms"]}
];

const filePath = path.join(process.cwd(), "src", "data", "countries.json");
const existing = JSON.parse(fs.readFileSync(filePath, "utf-8"));
const existingIso2 = new Set(existing.map((c: { iso2: string }) => c.iso2));

let added = 0;
for (const c of extra) {
  if (!existingIso2.has(c.iso2)) { existing.push(c); added++; }
}

fs.writeFileSync(filePath, JSON.stringify(existing, null, 2) + "\n");
console.log(`Added ${added}. Total: ${existing.length}`);
